log:
  level: info
routes:
  - path: /users
    methods:
      - POST
    stripPrefix: true
    backends:
      - http://im1:3001
      - http://im2:3002
      - http://im3:3003
  - path: /contacts
    methods:
      - GET
    stripPrefix: false
    backends:
      - http://im4:3004
      - http://im5:3005
limiter-conf:
  enabled: true
  shards: 32
  capacity: 2000
  refillRate: 2000
  ttl: 2m
  cleanUpTime: 1m
breaker-conf:
  failureThreshold: 3
  successThreshold: 3
  cooldown: 10s
  slowThreshold: 3s
