log:
  level: info
routes:
  - path: /users
    methods:
      - POST
    stripPrefix: true
    backends:
      - http://im1:3001
      - http://im2:3002
      - http://im3:3003
  - path: /contacts
    methods:
      - GET
    stripPrefix: false
    backends:
      - http://im4:3004
      - http://im5:3005
